jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Check Snippets
      run: python scripts/checksnippets.py
    - continue-on-error: true
      name: Copy mock google_services.json
      run: ./copy_mock_google_services_json.sh
    - continue-on-error: true
      if: github.event_name == 'pull_request'
      name: Build with Gradle (Pull Request)
      run: ./build_pull_request.sh
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Build with Gradle (Push)
      run: ./gradlew clean ktlint assemble
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
